; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "SOMS"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER '32"'
!define PRODUCT_WEB_SITE "https://www.soms.ssafy.com"

SetCompressor lzma

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "C:\Users\multicampus\Desktop\inho\PJT\Final\s03p31b303\deploy package\sampleIcon.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "C:\Users\multicampus\Desktop\inho\PJT\Final\s03p31b303\deploy package\install program\License.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\launcher.exe"
!define MUI_FINISHPAGE_SHOWREADME "$INSTDIR\readme.txt"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "Korean"

; Reserve files
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "somsInstall.exe"
InstallDir "$PROGRAMFILES\SOMS"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite on
  File "C:\Users\multicampus\Desktop\NSIS.7z"
  Nsis7z::Extract "$INSTDIR\NSIS.7z"
  Delete "$INSTDIR\NSIS.7z"
  File "C:\Users\multicampus\Desktop\inho\PJT\Final\s03p31b303\deploy package\install program\readme.txt"
  File "C:\Users\multicampus\Desktop\inho\PJT\Final\s03p31b303\deploy package\install program\mariadb-10.5.6-winx64.msi"
  File "C:\Users\multicampus\Desktop\inho\PJT\Final\s03p31b303\deploy package\install program\launcher.exe"
  CreateShortCut "$DESKTOP.lnk" "$INSTDIR\launcher.exe"
SectionEnd



Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name)는(은) 완전히 제거되었습니다."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "$(^Name)을(를) 제거하시겠습니까?" IDYES +2
  Abort
FunctionEnd
